# Generated by Django 3.2.4 on 2021-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schoollevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='birth_year',
            field=models.CharField(default='1930', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='postal',
            field=models.CharField(default='V5A 1S6', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='schoollevel',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='years_teaching',
            field=models.CharField(default='79', max_length=30),
        ),
    ]
