# Generated by Django 3.2.4 on 2021-07-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210729_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
