# Generated by Django 3.2.4 on 2021-07-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210729_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='years_teaching',
            new_name='years',
        ),
    ]
