# Generated by Django 3.2.4 on 2021-07-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_years_teaching_account_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='years',
            new_name='year',
        ),
    ]
