# Generated by Django 3.2.4 on 2021-07-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_years_account_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='schoollevel',
            new_name='level',
        ),
    ]
